services:

  tp:
    build: .
    container_name: kdb_tp
    hostname: ${KDB_HOSTNAME}
    command: q tick.q sym . -p 5010
    # share the host's physical network interface natively to reduce latency
    network_mode: "host"
    volumes:
      - ./kc.lic:/opt/q/kc.lic
      - ./tplog:/app/tplog
      - ./monitor.q:/app/monitor.q

  rdb:
    build: .
    container_name: kdb_rdb
    hostname: ${KDB_HOSTNAME}
    command: q r.q -p 5011
    depends_on:
      - tp
    network_mode: "host"
    environment:
      - HDB_PATH=/app/hdb
      - TP_HOST=127.0.0.1  # Changed from 'tp'
    volumes:
      - ./kc.lic:/opt/q/kc.lic
      - ./hdb:/app/hdb

  cep:
    build: .
    container_name: kdb_cep
    hostname: ${KDB_HOSTNAME}
    command: q cep.q -p 5012
    depends_on:
      - tp
    network_mode: "host"
    environment:
      - TP_HOST=127.0.0.1  # Changed from 'tp'
    volumes:
      - ./kc.lic:/opt/q/kc.lic

  feed-coinbase:
    build: .
    container_name: kdb_feed
    command: python coinbase_feedhandler.py
    depends_on:
      - tp
    network_mode: "host"
    environment:
      - TP_HOST=127.0.0.1  # Changed from 'tp'
      - TP_PORT=5010
      - COINBASE_KEY_FILE=/app/cdp_api_key.json
    volumes:
      - ./cdp_api_key.json:/app/cdp_api_key.json

  feed-kraken:
      build: .
      container_name: kdb_feed_kraken
      command: python kraken_feedhandler.py
      depends_on:
        - tp
      network_mode: "host"
      environment:
        - TP_HOST=127.0.0.1  # Changed from 'tp'
        - TP_PORT=5010

  mock-exchange:
    build: .
    container_name: kdb_mock_exchange
    command: python mock_exchange.py
    network_mode: "host"

  fix-gateway:
    build: .
    container_name: kdb_fix_gateway
    command: python fix_gateway.py
    depends_on:
      - rdb
      - mock-exchange
    network_mode: "host"
    environment:
      - KDB_HOST=127.0.0.1         # Changed from 'rdb'
      - KDB_PORT=5011
      - EXCHANGE_HOST=127.0.0.1    # Changed from 'mock-exchange'
      - EXCHANGE_PORT=9876

  dashboard:
    build: .
    container_name: kdb_dash
    command: streamlit run dashboard.py --server.port 8501
    depends_on:
      - cep
    network_mode: "host"
    environment:
      - CEP_HOST=127.0.0.1         # Changed from 'cep'

  prometheus:
    image: prom/prometheus
    container_name: kdb_prometheus
    network_mode: "host"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: kdb_grafana
    network_mode: "host"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin